// Official MICCAI subject areas -> Traditional Chinese labels.
window.M = window.M || {};
M.AXES = [
  ["Body", "部位"], ["Modalities", "影像模態"], ["Applications", "應用"],
  ["Surgery", "手術"], ["Machine Learning", "機器學習"], ["Special Topic", "特別主題"],
];
M.TOPIC_ZH = {
  "Abdomen": "腹部", "Brain": "腦", "Breast": "乳房", "Cardiac": "心臟", "Eye": "眼", "Fetal / Pediatric": "胎兒／兒科",
  "Head & Neck": "頭頸", "Lung / Thoracic": "肺／胸腔", "Musculoskeletal / Orthopedic": "肌肉骨骼／骨科",
  "Pelvis / Reproductive System": "骨盆／生殖系統", "Skin": "皮膚", "Spine": "脊椎", "Vasculature": "血管",
  "Whole-body / Multi-organ / Other": "全身／多器官／其他",
  "CT / X-ray": "CT／X 光", "Diffusion MRI": "擴散 MRI", "Digital Pathology/Histopathology": "數位病理／組織病理",
  "EEG / MEG / ECG / Physiological Signals": "EEG／MEG／ECG／生理訊號", "Electronic Health Records": "電子病歷",
  "Endoscopy": "內視鏡", "Functional MRI": "功能性 MRI", "MRI": "MRI", "Microscopy": "顯微影像",
  "Mobile / Wearable / Point-of-Care Imaging & Sensors": "行動／穿戴／床邊影像與感測",
  "Multimodal Sensor Fusion": "多模態感測融合", "Nuclear Imaging / PET / SPECT": "核醫／PET／SPECT",
  "Photograph / Video": "照片／影片", "Robotics / Intraoperative Imaging": "機器人／術中影像", "Spectroscopy": "光譜",
  "Synthetic / Computational Imaging": "合成／計算影像", "Ultrasound": "超音波",
  "Anomaly / Lesion Detection": "異常／病灶偵測", "Computational / Integrative Pathology": "計算／整合病理",
  "Computational Anatomy & Physiology": "計算解剖與生理", "Computer-Aided Diagnosis": "電腦輔助診斷",
  "Connectivity & Network Analysis": "連結與網路分析", "Digital Twins / Simulation / Synthetic Data": "數位孿生／模擬／合成資料",
  "Federated / Privacy-Preserving Analysis": "聯邦／隱私保護分析", "Image Reconstruction": "影像重建",
  "Image Registration": "影像配準", "Image Segmentation": "影像分割",
  "Image Synthesis / Augmentation / Super-Resolution": "影像合成／增強／超解析", "Image-Guided Interventions": "影像導引介入",
  "Medical Robotics": "醫療機器人", "Multimodal Integration with Clinical / Genomic / Biomarkers": "多模態整合（臨床／基因／生物標記）",
  "Neuropsychiatry & Mental Health Imaging": "神經精神與心理健康影像",
  "Outcome Prediction / Prognosis / Longitudinal Modeling": "預後預測／縱貫建模",
  "Public Health Imaging & Epidemiology": "公衛影像與流行病學", "Visualization in Biomedical Imaging": "生醫影像視覺化",
  "Data Science in Surgery": "手術資料科學", "Human-Robot Interaction & Autonomous Systems": "人機互動與自主系統",
  "Mixed / Augmented / Virtual Reality": "混合／擴增／虛擬實境", "Navigation": "導航", "Planning & Simulation": "規劃與模擬",
  "Scene Understanding": "場景理解", "Surgical Skills, Workflow & Team Dynamics": "手術技巧、流程與團隊",
  "Algorithmic Fairness / Safety / Regulation": "演算法公平／安全／法規", "Causal Inference / Counterfactual Reasoning": "因果推論／反事實推理",
  "Continual / Lifelong Learning": "持續學習", "Deep Learning": "深度學習", "Domain Adaptation / Harmonization": "領域適應／資料協調",
  "Evaluation / Benchmarking / Reproducibility": "評估／基準／再現性", "Fairness / Safety / Reliability": "公平／安全／可靠性",
  "Foundation Models": "基礎模型", "Interpretability / Explainability": "可解釋性", "Multimodal Models / LLMs / VLMs": "多模態模型／LLM／VLM",
  "Pathomics": "病理組學", "Radiomics / Radiogenomics": "影像組學／影像基因組學",
  "Reinforcement Learning / Control / Decision-Making": "強化學習／控制／決策",
  "Semi- / Weakly- / Self-supervised Learning": "半／弱／自監督學習", "Synthetic Data / Data-centric AI": "合成資料／資料中心 AI",
  "Uncertainty Quantification": "不確定性量化",
  "AI for Neglected Diseases & Limited-Resource Settings": "被忽視疾病與資源受限 AI",
  "AI for Population Health, Public Health & Epidemiology": "族群健康、公衛與流病 AI",
  "Clinical Trials & Deployment": "臨床試驗與部署", "Low-Cost / Point-of-Care Imaging": "低成本／床邊影像",
  "Telemedicine & Mobile Health Imaging": "遠距醫療與行動健康影像", "Other": "其他",
};
M.topicLabel = (t) => { const leaf = t.split(" -> ")[1] || t; return M.TOPIC_ZH[leaf] || leaf; };
